import type { MeetingReferenceLocaleKey } from "./meeting-reference-locales.js";

const groups: readonly [MeetingReferenceLocaleKey, readonly string[]][] = [
  ["panel.systemNoSignal", ["SYSTEM_AUDIO_NO_SIGNAL"]],
  ["panel.error.systemCheck", ["SYSTEM_AUDIO_PERMISSION_REQUIRED"]],
  ["panel.error.unsupported", ["SYSTEM_AUDIO_UNSUPPORTED", "SYSTEM_AUDIO_NOT_AVAILABLE"]],
  ["panel.micDenied", ["MICROPHONE_PERMISSION_DENIED", "MICROPHONE_PERMISSION_REQUIRED"]],
  ["panel.systemDenied", ["SYSTEM_AUDIO_PERMISSION_DENIED"]],
  ["panel.error.models", ["MODEL_NOT_READY", "MODEL_PACK_INCOMPATIBLE", "MODEL_PACK_INVALID", "ASSET_MISMATCH", "MODEL_LOAD_FAILED"]],
  ["panel.error.component", ["NATIVE_LOAD_FAILED", "NATIVE_FAILURE", "HELPER_ADHOC_ONLY", "HELPER_ASSET_INVALID", "HELPER_ASSET_MISSING", "HELPER_HASH_MISMATCH", "HELPER_MANIFEST_INVALID", "HELPER_RUNTIME_MISMATCH", "HELPER_SIGNATURE_IDENTITY_MISMATCH", "HELPER_SIGNATURE_INSPECTION_FAILED", "HELPER_SIGNATURE_INVALID", "HELPER_TREE_MISMATCH"]],
  ["panel.error.worker", ["WORKER_PROTOCOL_ERROR", "WORKER_PROCESS_ERROR", "WORKER_TIMEOUT", "MODEL_INFERENCE_FAILED"]],
  ["panel.error.helper", ["HELPER_PROCESS_ERROR", "HELPER_PROTOCOL_ERROR", "HELPER_READY_TIMEOUT", "HELPER_COMMAND_TIMEOUT", "HELPER_TERMINATION_TIMEOUT", "COMMAND_APPLY_FAILED", "MIC_CAPTURE_FAILED", "SYSTEM_CAPTURE_FAILED", "CAPTURE_PROCESS_ERROR", "CAPTURE_EXITED", "CAPTURE_LAUNCH_FAILED", "CAPTURE_REGISTRY_FAILED", "CAPTURE_START_TIMEOUT", "HELPER_START_FAILED", "ALL_REQUESTED_TRACKS_FAILED", "COMMAND_SCHEMA_INVALID", "COMMAND_SEQUENCE_INVALID"]],
  ["panel.error.permissionCheck", ["PERMISSION_CHECK_FAILED", "PERMISSION_CHECK_TIMEOUT", "MICROPHONE_PERMISSION_TIMEOUT"]],
  ["panel.error.storage", ["STORAGE_FAILURE", "HELPER_IO_FAILED", "AUDIO_READ_FAILED", "AUDIO_CHUNK_INVALID", "DISK_SPACE_INSUFFICIENT", "DATABASE_INTEGRITY_FAILED"]],
  ["panel.error.busy", ["ENGINE_BUSY", "DATA_ROOT_IN_USE"]],
  ["panel.error.resources", ["RESOURCE_LIMIT"]],
  ["panel.error.cancelled", ["CANCELLED_BY_USER", "WORKER_CANCELLED", "STAGE_ABORTED"]],
  ["panel.error.state", ["INVALID_INPUT", "INVALID_REQUEST", "INVALID_MEETING_STATE", "MEETING_NOT_FOUND", "TRANSCRIPT_VERSION_CONFLICT", "RUN_STATE_CONFLICT"]],
];

export function recordingErrorCopy(code: string, translate: (key: MeetingReferenceLocaleKey) => string): string {
  return translate(groups.find(([, codes]) => codes.includes(code))?.[0] ?? "panel.error.generic");
}
